name: Generate Monkeytype Readme Stats

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Generate Monkeytype Readme (Final Attempt)
        uses: monkeytype-hub/monkeytype-readme@master
        with:
          # REQUIRED: Your Monkeytype Username
          username: jason-silva
          # Pass the GITHUB_TOKEN directly to this action
          github-token: ${{ secrets.GITHUB_TOKEN }}
          
      # Since the first action does the commit now, we remove the second commit action
      # The first action is responsible for saving the file to the 'target-branch'.
